# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml/v1/predict.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ml/v1/predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ml/v1/predict.proto\x12\x15recommendationService\"e\n\x16RecommendationsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12:\n\rservey_reting\x18\x02 \x03(\x0b\x32#.recommendationService.ServeyReting\"V\n\x0cServeyReting\x12\x10\n\x08movie_id\x18\x01 \x01(\x05\x12\x13\n\x06rating\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x14\n\x0c\x66lag_watched\x18\x03 \x01(\x08\x42\t\n\x07_rating\"@\n\x17RecommendationsResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61rr_movie_id\x18\x02 \x03(\x05\x32\x8c\x01\n\x15RecommendationService\x12s\n\x12GetRecommendations\x12-.recommendationService.RecommendationsRequest\x1a..recommendationService.RecommendationsResponseB9Z7github.com/L1irik259/contracts/genetation/go/ml/v1;mlv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml.v1.predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/L1irik259/contracts/genetation/go/ml/v1;mlv1'
  _globals['_RECOMMENDATIONSREQUEST']._serialized_start=46
  _globals['_RECOMMENDATIONSREQUEST']._serialized_end=147
  _globals['_SERVEYRETING']._serialized_start=149
  _globals['_SERVEYRETING']._serialized_end=235
  _globals['_RECOMMENDATIONSRESPONSE']._serialized_start=237
  _globals['_RECOMMENDATIONSRESPONSE']._serialized_end=301
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=304
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=444
# @@protoc_insertion_point(module_scope)
