// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: ml/v1/predict.proto

package mlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServeyReting  []*ServeyReting        `protobuf:"bytes,2,rep,name=servey_reting,json=serveyReting,proto3" json:"servey_reting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationsRequest) Reset() {
	*x = RecommendationsRequest{}
	mi := &file_ml_v1_predict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsRequest) ProtoMessage() {}

func (x *RecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_v1_predict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsRequest.ProtoReflect.Descriptor instead.
func (*RecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_ml_v1_predict_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendationsRequest) GetServeyReting() []*ServeyReting {
	if x != nil {
		return x.ServeyReting
	}
	return nil
}

type ServeyReting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MovieId       int32                  `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Rating        *int32                 `protobuf:"varint,2,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	FlagWatched   bool                   `protobuf:"varint,3,opt,name=flag_watched,json=flagWatched,proto3" json:"flag_watched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeyReting) Reset() {
	*x = ServeyReting{}
	mi := &file_ml_v1_predict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeyReting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeyReting) ProtoMessage() {}

func (x *ServeyReting) ProtoReflect() protoreflect.Message {
	mi := &file_ml_v1_predict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeyReting.ProtoReflect.Descriptor instead.
func (*ServeyReting) Descriptor() ([]byte, []int) {
	return file_ml_v1_predict_proto_rawDescGZIP(), []int{1}
}

func (x *ServeyReting) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

func (x *ServeyReting) GetRating() int32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *ServeyReting) GetFlagWatched() bool {
	if x != nil {
		return x.FlagWatched
	}
	return false
}

type RecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArrMovieId    []int32                `protobuf:"varint,2,rep,packed,name=arr_movie_id,json=arrMovieId,proto3" json:"arr_movie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationsResponse) Reset() {
	*x = RecommendationsResponse{}
	mi := &file_ml_v1_predict_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsResponse) ProtoMessage() {}

func (x *RecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_v1_predict_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsResponse.ProtoReflect.Descriptor instead.
func (*RecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_ml_v1_predict_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendationsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendationsResponse) GetArrMovieId() []int32 {
	if x != nil {
		return x.ArrMovieId
	}
	return nil
}

var File_ml_v1_predict_proto protoreflect.FileDescriptor

const file_ml_v1_predict_proto_rawDesc = "" +
	"\n" +
	"\x13ml/v1/predict.proto\x12\x15recommendationService\"{\n" +
	"\x16RecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12H\n" +
	"\rservey_reting\x18\x02 \x03(\v2#.recommendationService.ServeyRetingR\fserveyReting\"t\n" +
	"\fServeyReting\x12\x19\n" +
	"\bmovie_id\x18\x01 \x01(\x05R\amovieId\x12\x1b\n" +
	"\x06rating\x18\x02 \x01(\x05H\x00R\x06rating\x88\x01\x01\x12!\n" +
	"\fflag_watched\x18\x03 \x01(\bR\vflagWatchedB\t\n" +
	"\a_rating\"T\n" +
	"\x17RecommendationsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\farr_movie_id\x18\x02 \x03(\x05R\n" +
	"arrMovieId2\x8c\x01\n" +
	"\x15RecommendationService\x12s\n" +
	"\x12GetRecommendations\x12-.recommendationService.RecommendationsRequest\x1a..recommendationService.RecommendationsResponseB6Z4github.com/L1irik259/contracts/genetation/go/v1;mlv1b\x06proto3"

var (
	file_ml_v1_predict_proto_rawDescOnce sync.Once
	file_ml_v1_predict_proto_rawDescData []byte
)

func file_ml_v1_predict_proto_rawDescGZIP() []byte {
	file_ml_v1_predict_proto_rawDescOnce.Do(func() {
		file_ml_v1_predict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_v1_predict_proto_rawDesc), len(file_ml_v1_predict_proto_rawDesc)))
	})
	return file_ml_v1_predict_proto_rawDescData
}

var file_ml_v1_predict_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ml_v1_predict_proto_goTypes = []any{
	(*RecommendationsRequest)(nil),  // 0: recommendationService.RecommendationsRequest
	(*ServeyReting)(nil),            // 1: recommendationService.ServeyReting
	(*RecommendationsResponse)(nil), // 2: recommendationService.RecommendationsResponse
}
var file_ml_v1_predict_proto_depIdxs = []int32{
	1, // 0: recommendationService.RecommendationsRequest.servey_reting:type_name -> recommendationService.ServeyReting
	0, // 1: recommendationService.RecommendationService.GetRecommendations:input_type -> recommendationService.RecommendationsRequest
	2, // 2: recommendationService.RecommendationService.GetRecommendations:output_type -> recommendationService.RecommendationsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ml_v1_predict_proto_init() }
func file_ml_v1_predict_proto_init() {
	if File_ml_v1_predict_proto != nil {
		return
	}
	file_ml_v1_predict_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_v1_predict_proto_rawDesc), len(file_ml_v1_predict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_v1_predict_proto_goTypes,
		DependencyIndexes: file_ml_v1_predict_proto_depIdxs,
		MessageInfos:      file_ml_v1_predict_proto_msgTypes,
	}.Build()
	File_ml_v1_predict_proto = out.File
	file_ml_v1_predict_proto_goTypes = nil
	file_ml_v1_predict_proto_depIdxs = nil
}
